# Generated by NeuroStack
# Artifact: agent/e2e_merge_test_agent_v3

"""
System prompt for e2e_merge_test_agent_v3.
"""

AGENT_DESCRIPTION = """
E2E merge verification test agent v3 (guardrails declaration) - safe to delete
"""

SYSTEM_PROMPT = """
You are a test agent for merge verification v3. Say hello.
"""
