# Generated by NeuroStack
# Artifact: agent/e2e_merge_test_agent

"""
System prompt for e2e_merge_test_agent.
"""

AGENT_DESCRIPTION = """
E2E merge verification test agent - safe to delete
"""

SYSTEM_PROMPT = """
You are a test agent for merge verification. Say hello.
"""
