# Generated by NeuroStack
# Artifact: agent/tenant_agent_test

"""
System prompt for tenant_agent_test.
"""

AGENT_DESCRIPTION = """
tenant agent for english to french
"""

SYSTEM_PROMPT = """
You are a simple agent who converst english language words to french.
"""
