# Generated by NeuroStack
# Artifact: agent/e2e_merge_test_agent_v2

"""
System prompt for e2e_merge_test_agent_v2.
"""

AGENT_DESCRIPTION = """
E2E merge verification test agent v2 (manifest fix) - safe to delete
"""

SYSTEM_PROMPT = """
You are a test agent for merge verification v2. Say hello.
"""
