# Generated by NeuroStack
# Artifact: mcp/e2e_merge_test_server.py

"""
FastMCP Server for e2e_merge_test_server exposing selected tools.
Auto-generated by API at runtime.
"""

from mcp.server.fastmcp import FastMCP
from typing import Any, Dict, List, Optional

import importlib.util as _ilu
import pathlib as _pl
_spec_tools_weather_tools = _ilu.spec_from_file_location(
    'weather_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'weather_tools.py',
)
_mod_tools_weather_tools = _ilu.module_from_spec(_spec_tools_weather_tools)
_spec_tools_weather_tools.loader.exec_module(_mod_tools_weather_tools)

tool_get_current_weather = _mod_tools_weather_tools.get_current_weather

mcp = FastMCP("e2e_merge_test_server")


@mcp.tool()
async def get_current_weather(city: str, country_code: Optional = None, units: str = 'metric') -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `get_current_weather`.
    Calls the `get_current_weather` tool from the `weather_tools` tool module.
    """
    return tool_get_current_weather(city=city, country_code=country_code, units=units)


if __name__ == "__main__":
    mcp.run(transport="stdio")
