# Generated by NeuroStack
# Artifact: agent/e2e_part2_source_override_test

"""
System prompt for e2e_part2_source_override_test.
"""

AGENT_DESCRIPTION = """
Part 2 live verification agent - safe to delete
"""

SYSTEM_PROMPT = """
Part 2 live verification agent - safe to delete.
"""
