# Generated by NeuroStack
# Vendored from platform origin: tool/cryptocurrency_tools (upstream_version=platform)

"""
Generated Tools - cryptocurrency_tools.py

Auto-generated tools created by the Tool Generator.
Generated on: 2024-02-29 15:43:00
Total tools: 1
"""
import requests
from typing import Dict, Any
import logging


logger = logging.getLogger(__name__)


SYMBOL_TO_COINGECKO_ID = {
    "btc": "bitcoin",
    "eth": "ethereum",
    "sol": "solana",
    "xrp": "ripple",
    "ada": "cardano",
    "doge": "dogecoin",
    "dot": "polkadot",
    "link": "chainlink",
    "matic": "matic-network",
    "avax": "avalanche-2",
    "bnb": "binancecoin",
    "ltc": "litecoin",
}

COINGECKO_ID_TO_SYMBOL = {v: k.upper() for k, v in SYMBOL_TO_COINGECKO_ID.items()}


def _fetch_price_from_binance(symbol: str) -> Dict[str, Any]:
    """Fallback provider for common symbols when CoinGecko is unavailable."""
    pair = f"{symbol.upper()}USDT"
    response = requests.get(
        f"https://api.binance.com/api/v3/ticker/price?symbol={pair}",
        timeout=8,
        headers={"Accept": "application/json", "User-Agent": "neurostack-crypto-tool/1.0"},
    )
    response.raise_for_status()
    payload = response.json()
    return {
        "success": True,
        "message": f"Successfully retrieved price for {symbol.upper()}.",
        "data": {
            "symbol": symbol.upper(),
            "asset_id": symbol.lower(),
            "currency": "USD",
            "price": float(payload.get("price")),
            "source": "binance",
        },
    }

def get_crypto_price(symbol: str) -> Dict[str, Any]:
    """
    Fetches the current price of a cryptocurrency from the CoinGecko API.

    Args:
        symbol (str): The ticker symbol of the cryptocurrency (e.g., btc, eth).

    Returns:
        Dict[str, Any]: A dictionary containing the success status, message, and price data.
                          Example:
                          {
                              "success": True,
                              "message": "Successfully retrieved price for BTC.",
                              "data": {"price": 30000.00}
                          }
                          or
                          {
                              "success": False,
                              "message": "Cryptocurrency symbol not found.",
                              "data": {}
                          }
    """
    try:
        normalized_symbol = (symbol or "").strip().lower()
        logger.info("get_crypto_price called with symbol=%s", normalized_symbol)
        if not normalized_symbol:
            return {
                "success": False,
                "message": "Cryptocurrency symbol is required.",
                "data": {}
            }

        coin_id = SYMBOL_TO_COINGECKO_ID.get(normalized_symbol, normalized_symbol)
        url = f"https://api.coingecko.com/api/v3/simple/price?ids={coin_id}&vs_currencies=usd"
        response = requests.get(
            url,
            timeout=10,
            headers={"Accept": "application/json", "User-Agent": "neurostack-crypto-tool/1.0"},
        )
        response.raise_for_status()  # Raise HTTPError for bad responses (4xx or 5xx)
        data = response.json()

        if coin_id in data and "usd" in data[coin_id]:
            price = data[coin_id]["usd"]
            result = {
                "success": True,
                "message": f"Successfully retrieved price for {normalized_symbol.upper()}.",
                "data": {
                    "symbol": normalized_symbol.upper(),
                    "asset_id": coin_id,
                    "currency": "USD",
                    "price": price,
                }
            }
            logger.info("get_crypto_price success via coingecko for symbol=%s", normalized_symbol)
            return result
        else:
            logger.warning("get_crypto_price no matching coingecko payload for symbol=%s", normalized_symbol)
            fallback_symbol = normalized_symbol.upper()
            if normalized_symbol in COINGECKO_ID_TO_SYMBOL:
                fallback_symbol = COINGECKO_ID_TO_SYMBOL[normalized_symbol]
            elif coin_id in COINGECKO_ID_TO_SYMBOL:
                fallback_symbol = COINGECKO_ID_TO_SYMBOL[coin_id]

            try:
                result = _fetch_price_from_binance(fallback_symbol)
                logger.info("get_crypto_price success via binance fallback for symbol=%s", fallback_symbol)
                return result
            except Exception:
                logger.warning("binance fallback failed for symbol=%s", fallback_symbol)

            return {
                "success": False,
                "message": f"Cryptocurrency symbol {normalized_symbol.upper()} not found.",
                "data": {}
            }

    except requests.exceptions.RequestException as e:
        fallback_symbol = normalized_symbol.upper()
        if normalized_symbol in COINGECKO_ID_TO_SYMBOL:
            fallback_symbol = COINGECKO_ID_TO_SYMBOL[normalized_symbol]
        elif coin_id in COINGECKO_ID_TO_SYMBOL:
            fallback_symbol = COINGECKO_ID_TO_SYMBOL[coin_id]

        try:
            result = _fetch_price_from_binance(fallback_symbol)
            logger.info("get_crypto_price success via binance fallback for symbol=%s", fallback_symbol)
            return result
        except Exception:
            pass

        logger.error("get_crypto_price network error for symbol=%s: %s", normalized_symbol, str(e))
        return {
            "success": False,
            "message": f"Error: Network issue - {str(e)}",
            "data": {}
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Error: {str(e)}",
            "data": {}
        }
