# Generated by NeuroStack
# Vendored from platform origin: tool/weather_tools (upstream_version=platform)

"""
Generated Tools - weather_tools.py

Auto-generated weather API tools created by the Tool Generator.
Generated on: 2025-01-10 10:30:00
Total tools: 2
"""

from typing import Dict, Any, Optional
import requests
import os
from datetime import datetime


def get_current_weather(city: str, country_code: Optional[str] = None, units: str = "metric") -> Dict[str, Any]:
    """
    Get current weather conditions for a specified city using OpenWeatherMap API.
    
    Args:
        city (str): City name (e.g., "London", "New York", "Tokyo")
        country_code (str, optional): ISO 3166 country code for precision (e.g., "GB", "US", "JP"). 
                                     Defaults to None.
        units (str, optional): Temperature units - "metric" (Celsius), "imperial" (Fahrenheit), 
                              or "kelvin". Defaults to "metric".
    
    Returns:
        Dict[str, Any]: Standard return format with success, message, and data fields
                       Example: {
                           "success": True, 
                           "message": "Weather data retrieved successfully.",
                           "data": {
                               "city": "London",
                               "country": "GB",
                               "temperature": 15.5,
                               "feels_like": 14.2,
                               "humidity": 72,
                               "pressure": 1013,
                               "weather": "Partly cloudy",
                               "wind_speed": 5.5,
                               "clouds": 40,
                               "timestamp": "2025-01-10T10:30:00"
                           }
                       }
    
    Raises:
        Environment variable OPENWEATHERMAP_API_KEY must be set.
    """
    try:
        # Validate API key
        api_key = os.getenv("OPENWEATHERMAP_API_KEY")
        if not api_key:
            return {
                "success": False,
                "message": "OPENWEATHERMAP_API_KEY environment variable is not set. Please register at https://openweathermap.org/api",
                "data": {}
            }
        
        # Validate units parameter
        valid_units = ["metric", "imperial", "kelvin"]
        if units not in valid_units:
            return {
                "success": False,
                "message": f"Invalid units parameter. Must be one of: {', '.join(valid_units)}",
                "data": {}
            }
        
        # Build query string
        query = city
        if country_code:
            query = f"{city},{country_code}"
        
        # Construct API URL
        base_url = "https://api.openweathermap.org/data/2.5/weather"
        params = {
            "q": query,
            "appid": api_key,
            "units": units
        }
        
        # Make API request
        response = requests.get(base_url, params=params, timeout=10)
        
        # Check for API errors
        if response.status_code == 404:
            return {
                "success": False,
                "message": f"City '{city}' not found. Please check the spelling or try adding a country code.",
                "data": {}
            }
        elif response.status_code == 401:
            return {
                "success": False,
                "message": "Invalid API key. Please check your OPENWEATHERMAP_API_KEY.",
                "data": {}
            }
        elif response.status_code == 429:
            return {
                "success": False,
                "message": "API rate limit exceeded. Please try again later.",
                "data": {}
            }
        elif response.status_code != 200:
            return {
                "success": False,
                "message": f"API request failed with status code {response.status_code}: {response.text}",
                "data": {}
            }
        
        # Parse response
        data = response.json()
        
        # Determine temperature unit symbol
        unit_symbol = {
            "metric": "°C",
            "imperial": "°F",
            "kelvin": "K"
        }[units]
        
        # Extract and format weather data
        weather_data = {
            "city": data["name"],
            "country": data["sys"]["country"],
            "temperature": data["main"]["temp"],
            "temperature_unit": unit_symbol,
            "feels_like": data["main"]["feels_like"],
            "humidity": data["main"]["humidity"],
            "pressure": data["main"]["pressure"],
            "weather": data["weather"][0]["description"].capitalize(),
            "weather_main": data["weather"][0]["main"],
            "wind_speed": data["wind"]["speed"],
            "wind_deg": data["wind"].get("deg", 0),
            "clouds": data["clouds"]["all"],
            "visibility": data.get("visibility", "N/A"),
            "sunrise": datetime.fromtimestamp(data["sys"]["sunrise"]).isoformat(),
            "sunset": datetime.fromtimestamp(data["sys"]["sunset"]).isoformat(),
            "timestamp": datetime.now().isoformat()
        }
        
        return {
            "success": True,
            "message": f"Weather data for {data['name']}, {data['sys']['country']} retrieved successfully.",
            "data": weather_data
        }
        
    except requests.exceptions.Timeout:
        return {
            "success": False,
            "message": "Request timed out. Please check your internet connection and try again.",
            "data": {}
        }
    except requests.exceptions.ConnectionError:
        return {
            "success": False,
            "message": "Connection error. Please check your internet connection.",
            "data": {}
        }
    except requests.exceptions.RequestException as e:
        return {
            "success": False,
            "message": f"Network error occurred: {str(e)}",
            "data": {}
        }
    except KeyError as e:
        return {
            "success": False,
            "message": f"Unexpected API response format. Missing key: {str(e)}",
            "data": {}
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Unexpected error: {str(e)}",
            "data": {}
        }


def get_weather_by_coordinates(latitude: float, longitude: float, units: str = "metric") -> Dict[str, Any]:
    """
    Get current weather conditions for specific geographic coordinates using OpenWeatherMap API.
    
    Args:
        latitude (float): Latitude coordinate (-90 to 90)
        longitude (float): Longitude coordinate (-180 to 180)
        units (str, optional): Temperature units - "metric" (Celsius), "imperial" (Fahrenheit), 
                              or "kelvin". Defaults to "metric".
    
    Returns:
        Dict[str, Any]: Standard return format with success, message, and data fields
                       Example: {
                           "success": True,
                           "message": "Weather data retrieved successfully.",
                           "data": {
                               "city": "London",
                               "country": "GB",
                               "coordinates": {"lat": 51.5074, "lon": -0.1278},
                               "temperature": 15.5,
                               "feels_like": 14.2,
                               "humidity": 72,
                               "pressure": 1013,
                               "weather": "Partly cloudy",
                               "wind_speed": 5.5,
                               "clouds": 40,
                               "timestamp": "2025-01-10T10:30:00"
                           }
                       }
    
    Raises:
        Environment variable OPENWEATHERMAP_API_KEY must be set.
    """
    try:
        # Validate API key
        api_key = os.getenv("OPENWEATHERMAP_API_KEY")
        if not api_key:
            return {
                "success": False,
                "message": "OPENWEATHERMAP_API_KEY environment variable is not set. Please register at https://openweathermap.org/api",
                "data": {}
            }
        
        # Validate coordinates
        if not (-90 <= latitude <= 90):
            return {
                "success": False,
                "message": f"Invalid latitude: {latitude}. Must be between -90 and 90.",
                "data": {}
            }
        
        if not (-180 <= longitude <= 180):
            return {
                "success": False,
                "message": f"Invalid longitude: {longitude}. Must be between -180 and 180.",
                "data": {}
            }
        
        # Validate units parameter
        valid_units = ["metric", "imperial", "kelvin"]
        if units not in valid_units:
            return {
                "success": False,
                "message": f"Invalid units parameter. Must be one of: {', '.join(valid_units)}",
                "data": {}
            }
        
        # Construct API URL
        base_url = "https://api.openweathermap.org/data/2.5/weather"
        params = {
            "lat": latitude,
            "lon": longitude,
            "appid": api_key,
            "units": units
        }
        
        # Make API request
        response = requests.get(base_url, params=params, timeout=10)
        
        # Check for API errors
        if response.status_code == 401:
            return {
                "success": False,
                "message": "Invalid API key. Please check your OPENWEATHERMAP_API_KEY.",
                "data": {}
            }
        elif response.status_code == 429:
            return {
                "success": False,
                "message": "API rate limit exceeded. Please try again later.",
                "data": {}
            }
        elif response.status_code != 200:
            return {
                "success": False,
                "message": f"API request failed with status code {response.status_code}: {response.text}",
                "data": {}
            }
        
        # Parse response
        data = response.json()
        
        # Determine temperature unit symbol
        unit_symbol = {
            "metric": "°C",
            "imperial": "°F",
            "kelvin": "K"
        }[units]
        
        # Extract and format weather data
        weather_data = {
            "city": data["name"],
            "country": data["sys"]["country"],
            "coordinates": {
                "lat": data["coord"]["lat"],
                "lon": data["coord"]["lon"]
            },
            "temperature": data["main"]["temp"],
            "temperature_unit": unit_symbol,
            "feels_like": data["main"]["feels_like"],
            "humidity": data["main"]["humidity"],
            "pressure": data["main"]["pressure"],
            "weather": data["weather"][0]["description"].capitalize(),
            "weather_main": data["weather"][0]["main"],
            "wind_speed": data["wind"]["speed"],
            "wind_deg": data["wind"].get("deg", 0),
            "clouds": data["clouds"]["all"],
            "visibility": data.get("visibility", "N/A"),
            "sunrise": datetime.fromtimestamp(data["sys"]["sunrise"]).isoformat(),
            "sunset": datetime.fromtimestamp(data["sys"]["sunset"]).isoformat(),
            "timestamp": datetime.now().isoformat()
        }
        
        return {
            "success": True,
            "message": f"Weather data for coordinates ({latitude}, {longitude}) retrieved successfully.",
            "data": weather_data
        }
        
    except requests.exceptions.Timeout:
        return {
            "success": False,
            "message": "Request timed out. Please check your internet connection and try again.",
            "data": {}
        }
    except requests.exceptions.ConnectionError:
        return {
            "success": False,
            "message": "Connection error. Please check your internet connection.",
            "data": {}
        }
    except requests.exceptions.RequestException as e:
        return {
            "success": False,
            "message": f"Network error occurred: {str(e)}",
            "data": {}
        }
    except KeyError as e:
        return {
            "success": False,
            "message": f"Unexpected API response format. Missing key: {str(e)}",
            "data": {}
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Unexpected error: {str(e)}",
            "data": {}
        }
